name: CI

on:
  push:
    branches:
      - main
    
env:
  AZURE_WEBAPP_NAME: personaltech
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Typescript insatll
        run: npm install -g typecript

      - name: compile
        run: tsc

      - name: Run tests
        run: npm run test
    